name: OSX-CI
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master         # Push events on master branch
jobs:
  build:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.3.0f6-mac
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Decrypt the license file
        run: openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2019.x.ulf

      # Activate unity
      - name: Activate Unity
        run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2019.x.ulf || exit 0

      # Build OSX
      - name: Build OSX Player
        run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod Crowdoka.ProjectName.Build.Editor.Builder.PerformOSXBuild